"use strict";

module.exports = {
    all: "every",
    any: "some",
    backflow: "flowRight",
    callback: "iteratee",
    collect: "map",
    compose: "flowRight",
    contains: "includes",
    detect: "find",
    foldl: "reduce",
    foldr: "reduceRight",
    findWhere: "find",
    first: "head",
    include: "includes",
    indexBy: "keyBy",
    inject: "reduce",
    invoke: "invokeMap",
    modArgs: "overArgs",
    methods: "functions",
    object: "fromPairs",
    padLeft: "padStart",
    padRight: "padEnd",
    pairs: "toPairs",
    pluck: "map",
    rest: "tail",
    restParam: "rest",
    select: "filter",
    sortByOrder: "orderBy",
    support: undefined,
    trimLeft: "trimStart",
    trimRight: "trimEnd",
    trunc: "truncate",
    unique: "uniq",
    where: "filter",
};